---
- name: Create users and assign SSH keys from files
  hosts: myhosts
  become: yes
  vars:
    users:
      - username: alice
        is_admin: yes
        pub_key_path: "/path/to/keys/alice.pub"
      - username: bob
        is_admin: no
        pub_key_path: "/path/to/keys/bob.pub"
      - username: charlie
        is_admin: no
        pub_key_path: "/path/to/keys/charlie.pub"

  tasks:
    - name: Create user accounts
      user:
        name: "{{ item.username }}"
        state: present
        groups: "{{ 'sudo' if item.is_admin else '' }}"
        shell: /bin/bash
      loop: "{{ users }}"

    - name: Create .ssh directory for each user
      file:
        path: "/home/{{ item.username }}/.ssh"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0700'
      loop: "{{ users }}"

    - name: Copy SSH public key from file for each user
      copy:
        src: "{{ item.pub_key_path }}"
        dest: "/home/{{ item.username }}/.ssh/authorized_keys"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0600'
      loop: "{{ users }}"

    - name: Ensure sudo group has passwordless sudo (for admins)
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        state: present
      when: item.is_admin | bool
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.username }}"
