---
- name: Install and configure UFW and Fail2Ban
  hosts: myhosts
  become: yes

  vars:
    custom_port: 12345         # Replace this with your custom port number
    jail_local_src: "./JailConf"  # Path to your jail.local file

  tasks:
    - name: Ensure the system is Debian/Ubuntu based
      debug:
        msg: "This playbook is only supported on Debian/Ubuntu systems."
      when: ansible_facts['os_family'] != "Debian"
      failed_when: ansible_facts['os_family'] != "Debian"

    # UFW Configuration
    - name: Install UFW
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Set UFW default policy to deny incoming
      ufw:
        default: deny
        direction: incoming
        state: enabled

    - name: Set UFW default policy to allow outgoing
      ufw:
        default: allow
        direction: outgoing
        state: enabled

    - name: Allow custom port through UFW
      ufw:
        rule: allow
        port: "{{ custom_port }}"
        proto: tcp

    - name: Ensure UFW is enabled
      ufw:
        state: enabled

    # Fail2Ban Configuration
    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Check if jail.local file exists
      stat:
        path: "{{ jail_local_src }}"
      register: jail_local_check

    - name: Backup existing jail.local file
      copy:
        src: /etc/fail2ban/jail.local
        dest: /etc/fail2ban/jail.local.bak
        remote_src: yes
      when: jail_local_check.stat.exists

    - name: Copy custom jail.local configuration file if it exists
      copy:
        src: "{{ jail_local_src }}"
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      when: jail_local_check.stat.exists

    - name: Ensure Fail2Ban is running and enabled on boot
      service:
        name: fail2ban
        state: started
        enabled: yes
