#########DO NOT USE THIS FILE IT IS IN DEVELOPMENT############

---
- name: Install and configure Firewalld (Fedora-based systems)
  hosts: all
  become: yes

  vars:
    custom_port: 12345  # Replace this with your custom port number

  tasks:
    - name: Install firewalld
      dnf:
        name: firewalld
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure firewalld is running and enabled
      service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Set default firewalld policy to deny incoming and allow outgoing
      firewalld:
        default_zone: public
        state: enabled
        immediate: yes

    - name: Allow custom port through firewalld
      firewalld:
        port: "{{ custom_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
