---
- name: Install and configure Fail2Ban
  hosts: myhosts
  become: yes

  vars:
    jail_local_src: "files/jail.local"  # Path to your jail.local file

    - name: Install Fail2Ban (Debian-based systems)
      apt:
        name: fail2ban
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Fail2Ban (Fedora-based systems)
      dnf:
        name: fail2ban
        state: present
      when: ansible_os_family == "RedHat"

    - name: Copy custom jail.local configuration file
      copy:
        src: "{{ jail_local_src }}"
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Fail2Ban is running and enabled on boot
      service:
        name: fail2ban
        state: started
        enabled: yes
