
---
- name: Install and configure UFW
  hosts: all
  become: yes

  vars:
    custom_port: 12345  # Replace this with your custom port number

  tasks:
    - name: Install UFW
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Ensure UFW is enabled
      ufw:
        state: enabled

    - name: Set UFW default policy to deny incoming and allow outgoing
      ufw:
        state: enabled
        default: deny incoming
        direction: incoming

    - name: Set UFW default policy to allow outgoing
      ufw:
        state: enabled
        default: allow outgoing
        direction: outgoing

    - name: Allow custom port through UFW
      ufw:
        rule: allow
        port: "{{ custom_port }}"
        proto: tcp
